import typography from "@tailwindcss/typography";
import daisyui from "daisyui";

export default {
  darkMode: "class",
  content: ["./src/dashboard/ui/**/*.{html,ts,svelte}"],
  theme: {
    extend: {
      colors: {
        sprinty: {
          50: "#f0f9ff",
          100: "#e0f2fe",
          200: "#bae6fd",
          300: "#7dd3fc",
          400: "#38bdf8",
          500: "#0ea5e9",
          600: "#0284c7",
          700: "#0369a1",
          800: "#075985",
          900: "#0c4a6e",
          950: "#082f49",
        },
      },
      typography: () => ({
        zinc: {
          css: {
            "--tw-prose-body": "#3f3f46",
            "--tw-prose-headings": "#18181b",
            "--tw-prose-links": "#0284c7",
            "--tw-prose-code": "#0369a1",
            "--tw-prose-invert-body": "#d4d4d8",
            "--tw-prose-invert-headings": "#fafafa",
            "--tw-prose-invert-links": "#7dd3fc",
            "--tw-prose-invert-code": "#bae6fd",
          },
        },
      }),
    },
  },
  daisyui: {
    themes: [
      {
        sprinty: {
          "color-scheme": "light",
          primary: "#2563eb",
          "primary-content": "#eff6ff",
          secondary: "#0f766e",
          "secondary-content": "#ecfeff",
          accent: "#d97706",
          "accent-content": "#fffbeb",
          neutral: "#18181b",
          "neutral-content": "#fafafa",
          "base-100": "#ffffff",
          "base-200": "#f4f7fb",
          "base-300": "#d9e1ec",
          "base-content": "#18181b",
          info: "#0284c7",
          "info-content": "#f0f9ff",
          success: "#059669",
          "success-content": "#ecfdf5",
          warning: "#d97706",
          "warning-content": "#fffbeb",
          error: "#dc2626",
          "error-content": "#fef2f2",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.375rem",
          "--rounded-badge": "9999px",
        },
      },
      {
        sprintydark: {
          "color-scheme": "dark",
          primary: "#3b82f6",
          "primary-content": "#eff6ff",
          secondary: "#14b8a6",
          "secondary-content": "#ecfeff",
          accent: "#f59e0b",
          "accent-content": "#451a03",
          neutral: "#f4f4f5",
          "neutral-content": "#09090b",
          "base-100": "#0d1117",
          "base-200": "#111827",
          "base-300": "#253044",
          "base-content": "#f4f4f5",
          info: "#38bdf8",
          "info-content": "#082f49",
          success: "#34d399",
          "success-content": "#052e16",
          warning: "#fbbf24",
          "warning-content": "#451a03",
          error: "#f87171",
          "error-content": "#450a0a",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.375rem",
          "--rounded-badge": "9999px",
        },
      },
    ],
    darkTheme: "sprintydark",
  },
  plugins: [typography, daisyui],
};
